routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\EmployeeLoginController;
use App\Http\Controllers\CompanyEmployeeController;
use App\Http\Controllers\EmployeeDashboardController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;

Route::redirect('/', '/login');
Auth::routes(['register' => false]);
Route::get('lang/{lang}', [LocalizationController::class, 'lang'])->name('lang.switch');

Route::prefix('employee')->group(function () {
    Route::middleware('guest:employee')->group(function() {
        Route::get('login/{id}', [EmployeeLoginController::class, 'login'])->name('login.employee_view');
        Route::post('login/{id}', [EmployeeLoginController::class, 'store'])->name('login.employee');
    });
    
    Route::middleware('auth:employee')->group(function() {
        Route::post('logout', [EmployeeLoginController::class, 'logout'])->name('employee.logout');
        Route::get('dashboard/home', [EmployeeDashboardController::class, 'index'])->name('employee.dashboard');
        Route::get('dashboard/list', [EmployeeDashboardController::class, 'show']);
    });
});

Route::prefix('dashboard')->middleware('auth:web')->group(function () {
    Route::get('home',[DashboardController::class,'index']);
    Route::get('company/{company}/show-employee', [CompaniesController::class, 'showEmployee'])->name('company.employee');
    Route::get('summary', [SellSummaryController::class, 'index'])->name('summary.index');
    Route::get('summary-detail/{employee_id}/{date}', [SellSummaryController::class, 'detail'])->name('summary.detail');
    Route::resource('employee', CompanyEmployeeController::class);
    Route::resource('company', CompaniesController::class);
    Route::resource('item', ItemController::class);
    Route::resource('sell', SellController::class);
});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function sell()
    {
        return $this->hasMany(Sell::class);
    }

    public static function filter($filter,$query,$page)
    {
        return self::where("$filter", 'like', "%$query%")->latest()->paginate($page)->withQueryString();
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        return view('dashboard.index',[
            'title' => 'Dashboard'
        ]);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page = $request->paginate;
        $query = $request->string;

        if( $filter = $request->filter ) {
            if($filter == 'name' || $filter == 'price' || $filter == 'created_at') {
                $items = Item::filter($filter, $query, $page);
            } else {
                abort(404);
            }
        } else {
            $items = Item::latest()->paginate(5)->withQueryString();
        }

        return view('dashboard.item.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.item.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required'
        ]);

        Item::create($request->all());

        return redirect()->route('item.index')->with('success', __('flash.item_created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return view('dashboard.item.detail', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        return view('dashboard.item.update', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required'
        ]);

        $item->update($request->all());

        return redirect()->route('item.index')->with('success', __('flash.item_updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();

        return redirect()->route('item.index')->with('success', __('flash.item_removed'));
    }
}

resources/views/dashboard/item/create.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('item.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group mb-3">
                    <label for="name">{{ __('messages.item_name') }}</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="{{ __('messages.item_name') }}" autocomplete="off" value="{{ old('name') }}">
                    @error('name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="price">{{ __('messages.item_price') }}</label>
                    <input type="text" class="form-control" id="price" name="price" placeholder="199" autocomplete="off" value="{{ old('price') }}">
                    @error('price')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/item/detail.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title text-uppercase font-weight-bold">{{ $item->name }}</h3>
        </div>
        <div class="card-body">
            <ul class="mt-2">
                <li>{{ __('messages.item_name') }} : {{ $item->name }}</li>
                <li>{{ __('messages.item_price') }} : {{ $item->price }}</li>
            </ul>
        </div>
    </div>
@endsection

resources/views/dashboard/item/index.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="content">
    <div class="container ml-2">
        <div class="row">
            <div class="col-lg-12 mb-3">
                <a href="{{ route('item.create') }}" class="text-white"><button type="button" class="btn btn-dark">{{ __('messages.add_item') }}</a></button>
            </div>
            <div class="col-lg-6">
                <form action="{{ route('item.index') }}" method="GET">
                    <label for="slug" class="form-label">Paginate</label>
                    <input type="text" class="form-control mb-3" name="paginate" placeholder="{{ __('messages.paginate_per_page') }}" value="{{ request('paginate') }}">
                    <div class="mb-2">
                        <label for="timezone" class="form-label">{{ __('messages.time_zone') }}</label>
                        <select class="form-select" name="timezone">
                            @if(request('timezone'))
                            <option value="{{ request('timezone') }}" selected>{{ __('messages.selected') }} ({{ ucfirst(request('timezone')) }})</option>
                            @else
                            <option value="Etc/GMT" selected>Default (UTC)</option>
                            @endif
                            <option value="Etc/GMT">UTC</option>
                            <option value="Asia/Jakarta">Jakarta</option>
                            <option value="America/Cayenne">Cayenne</option>
                            <option value="Pacific/Honolulu">Hawaii</option>
                            <option value="Asia/Seoul">Seoul</option>
                        </select>
                    </div>
                    <div class="mb-2">
                        <label for="filter" class="form-label">Filter</label>
                        <select class="form-select" name="filter">
                            @if(request('filter'))
                            <option value="{{ request('filter') }}" selected>{{ __('messages.selected') }} ({{ __('messages.' . request('filter')) }})</option>
                            @else
                            <option value="name" selected>Default ({{ __('messages.item_name') }})</option>
                            @endif
                            <option value="name">{{ __('messages.item_name') }}</option>
                            <option value="price">{{ __('messages.item_price') }}</option>
                            <option value="created_at">{{ __('messages.created_at') }}</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="string" placeholder="{{ __('messages.search') }}" value="{{ request('string') }}">
                        <div class="input-group-append">
                            <button class="btn btn-outline-dark" type="submit">{{ __('messages.search') }}</button>
                        </div>
                    </div>  
                </form>
            </div>
            <div class="col-lg-12">
                @if($message = Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert" id="my-alert">
                        {!! session('success') !!}
                        <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                    </div>
                @endif
                <table id="company" class="display table">
                    <thead class="table-dark">
                        <tr>
                            <th>No</th>
                            <th>{{ __('messages.item_name') }}</th>
                            <th>{{ __('messages.item_price') }}</th>
                            <th>{{ __('messages.created_at') }}</th>
                            <th>{{ __('messages.action') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($items as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->price }}</td>
                            <td>{{ \Carbon\Carbon::parse($item->created_at)->setTimezone(request('timezone')) }}</td>
                            <td>
                                <form class="d-inline" action="{{ route('item.destroy',$item) }}" method="post">
                                    <a href="{{ route('item.show',$item) }}" class="btn btn-warning btn-sm"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('item.edit',$item) }}" class="btn btn-dark btn-sm"><i class="fas fa-edit"></i></a>
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger btn-sm" onclick="return confirm('{{ __('messages.confirm_to_delete_data') }}')" ><i class="fas fa-trash-alt"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $items->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/item/update.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('item.update', $item) }}" method="post" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="form-group mb-3">
                    <label for="name">{{ __('messages.item_name') }}</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="{{ __('messages.item_name') }}" autocomplete="off" value="{{ old('name', $item->name) }}">
                    @error('name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="price">{{ __('messages.item_price') }}</label>
                    <input type="text" class="form-control" id="price" name="price" placeholder="199" autocomplete="off" value="{{ old('price', $item->price) }}">
                    @error('price')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection