routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\EmployeeLoginController;
use App\Http\Controllers\CompanyEmployeeController;
use App\Http\Controllers\EmployeeDashboardController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;

Route::redirect('/', '/login');
Auth::routes(['register' => false]);
Route::get('lang/{lang}', [LocalizationController::class, 'lang'])->name('lang.switch');

Route::prefix('employee')->group(function () {
    Route::middleware('guest:employee')->group(function() {
        Route::get('login/{id}', [EmployeeLoginController::class, 'login'])->name('login.employee_view');
        Route::post('login/{id}', [EmployeeLoginController::class, 'store'])->name('login.employee');
    });
    
    Route::middleware('auth:employee')->group(function() {
        Route::post('logout', [EmployeeLoginController::class, 'logout'])->name('employee.logout');
        Route::get('dashboard/home', [EmployeeDashboardController::class, 'index'])->name('employee.dashboard');
        Route::get('dashboard/list', [EmployeeDashboardController::class, 'show']);
    });
});

Route::prefix('dashboard')->middleware('auth:web')->group(function () {
    Route::get('home',[DashboardController::class,'index']);
    Route::get('company/{company}/show-employee', [CompaniesController::class, 'showEmployee'])->name('company.employee');
    Route::get('summary', [SellSummaryController::class, 'index'])->name('summary.index');
    Route::get('summary-detail/{employee_id}/{date}', [SellSummaryController::class, 'detail'])->name('summary.detail');
    Route::resource('employee', CompanyEmployeeController::class);
    Route::resource('company', CompaniesController::class);
    Route::resource('item', ItemController::class);
    Route::resource('sell', SellController::class);
});

app/Models/Sell.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sell extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    protected $with = ['employee','item'];

    public function item()
    {
        return $this->belongsTo(Item::class);
    }

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    public static function filter($filter,$query,$start_date,$end_date)
    {
        if($filter == 'price' || $filter == 'discount') {
            if(!$start_date && !$end_date) {
                return self::where("$filter", 'like', "%$query%");
            } else {
                return self::where("$filter", 'like', "%$query%")->whereBetween('date', [$start_date,$end_date]);
            }
        }
        elseif($filter == 'date') {
            return self::whereBetween('date', [$start_date,$end_date]);
        } else {
            abort(404);
        }
    }

    public static function filterSellDetail($employee_id,$date)
    {
        return self::where([
            ['employee_id', $employee_id],
            ['date', 'like', "%$date%"]
        ])->latest()->paginate(5)->withQueryString();
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        return view('dashboard.index',[
            'title' => 'Dashboard'
        ]);
    }
}

app/Http/Controllers/SellController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Sell;
use App\Models\Employee;
use App\Models\SellSummary;
use Illuminate\Http\Request;

class SellController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page = $request->paginate;
        $start_date = $request->start_date;
        $end_date = $request->end_date;
        $query = $request->string;

        if($filter = $request->filter) {
            $sells = Sell::filter($filter, $query, $start_date, $end_date)->latest()->paginate($page)->withQueryString();
        } else {
            $sells = Sell::latest()->paginate(5);
        }

        return view('dashboard.sell.index', compact('sells'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.sell.create', [
            'items' => Item::all(),
            'employees' => Employee::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'date' => 'required',
            'item_id' => 'required',
            'price' => 'required',
            'discount' => 'required',
            'employee_id' => 'required'
        ]);

        Sell::create($request->all());

        $date = date('Y-m-d',strtotime($request->date));

        if( $summary = SellSummary::where(['employee_id' => $request->employee_id, 'date' => $date])->first()) {
            $summary->update([
                'price_total' => $summary->price_total + $request->price,
                'discount_total' => $summary->discount_total + ($request->price * $request->discount),
                'total' => $summary->total + $request->price - ($request->price * $request->discount),
                'updated_at' => date('Y-m-d H:i:s')
            ]);
        } else {
            SellSummary::create([
                'date' => $date,
                'employee_id' => $request->employee_id,
                'price_total' => $request->price,
                'discount_total' => ($request->price * $request->discount),
                'total' => $request->price - ($request->price * $request->discount)
            ]);
        }

        return redirect()->route('sell.index')->with('success', __('flash.sell_created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Sell  $sell
     * @return \Illuminate\Http\Response
     */
    public function show(Sell $sell)
    {
        return view('dashboard.sell.detail', compact('sell'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Sell  $sell
     * @return \Illuminate\Http\Response
     */
    public function edit(Sell $sell)
    {
        return view('dashboard.sell.update', [
            'items' => Item::all(),
            'employees' => Employee::all(),
            'sell' => $sell
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Sell  $sell
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sell $sell)
    {
        $input = $request->validate([
            'item_id' => 'required',
            'employee_id' => 'required',
            'price' => 'required',
            'discount' => 'required'
        ]);

        if( $request->date ) $input['date'] = $request->date;
        $input['price'] = $sell->price + $request->price;
        $input['discount'] = $sell->discount + $request->discount;


        // $sell_date = date('Y-m-d',strtotime($sell->date));
        // if($sell->employee_id != $request->employee_id ) {
        //     SellSummary::updateOldSummarySellData($sell,$sell_date);
        //     SellSummary::updateNewSummarySellData($request,$sell,$sell_date);
        // };

        $sell->update($input);


        $date = date('Y-m-d',strtotime($sell->date));

        if( $summary = SellSummary::where(['employee_id' => $request->employee_id, 'date' => $date])->first()) {
            $summary->update([
                'price_total' => $summary->price_total + $request->price,
                'discount_total' => $summary->discount_total + ($sell->price * $request->discount),
                'total' => $summary->total + $request->price - ($sell->price * $request->discount),
                'updated_at' => date('Y-m-d H:i:s')
            ]);
        } else {
            SellSummary::create([
                'date' => $date,
                'employee_id' => $request->employee_id,
                'price_total' => $sell->price,
                'discount_total' => $sell->discount * $sell->price,
                'total' => $sell->price - ($sell->discount * $sell->price)
            ]);
        }

        return redirect()->route('sell.index')->with('success', __('flash.sell_updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Sell  $sell
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sell $sell)
    {
        // $sell_date = date('Y-m-d',strtotime($sell->date));
        // SellSummary::updateOldSummarySellData($sell,$sell_date);

        $sell->delete();

        return redirect()->route('sell.index')->with('success', __('flash.sell_removed'));
    }
}

resources/views/dashboard/sell/create.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('sell.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="mb-3">
                    <label for="item_id" class="form-label">{{ __('messages.item_name') }}</label>
                    <select class="form-select" name="item_id">
                        @foreach($items as $item)
                            @if(old('item') == $item->id)
                                <option value="{{ $item->id }}" selected>{{ $item->name }}</option>
                            @else
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label for="employee_id" class="form-label">{{ __('messages.sell_by') }}</label>
                    <select class="form-select" name="employee_id">
                        @foreach($employees as $employee)
                            @if(old('employee') == $employee->id)
                                <option value="{{ $employee->id }}" selected>{{ $employee->first_name }}</option>
                            @else
                                <option value="{{ $employee->id }}">{{ $employee->first_name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group mb-3">
                    <label for="date">{{ __('messages.sell_date') }}</label>
                    <input type="datetime-local" class="form-control" id="date" name="date" autocomplete="off" value="{{ old('date') }}">
                    @error('date')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="price">{{ __('messages.sell_price') }}</label>
                    <input type="text" class="form-control" id="price" name="price" placeholder="80000" autocomplete="off" value="{{ old('price') }}">
                    @error('price')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="discount">{{ __('messages.sell_discount') }}</label>
                    <input type="text" class="form-control" id="discount" name="discount" placeholder="%" autocomplete="off" value="{{ old('discount') }}">
                    @error('discount')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/sell/detail.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title text-uppercase font-weight-bold">{{ __('messages.sell_by') }} {{ $sell->employee->first_name }}</h3>
        </div>
        <div class="card-body">
            <ul class="mt-2">
                <li>{{ __('messages.name') }} : {{ $sell->item->name }}</li>
                <li>{{ __('messages.price') }} : {{ $sell->price }}</li>
                <li>{{ __('messages.discount') }} : {{ $sell->discount }}</li>
                <li>{{ __('messages.sell_by') }} : {{ $sell->employee->first_name }}</li>
                <li>{{ __('messages.sell_date') }} : {{ $sell->date }}</li>
            </ul>
        </div>
    </div>
@endsection

resources/views/dashboard/sell/index.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="content">
    <div class="container ml-2">
        <div class="row">
            <div class="col-lg-12 mb-3">
                <a href="{{ route('sell.create') }}" class="text-white"><button type="button" class="btn btn-dark">{{ __('messages.add_sell') }}</a></button>
            </div>
            <div class="col-lg-6">
                <form action="{{ route('sell.index') }}" method="GET">
                    <label for="slug" class="form-label">Paginate</label>
                    <input type="text" class="form-control mb-3" name="paginate" placeholder="{{ __('messages.paginate_per_page') }}" value="{{ request('paginate') }}">
                    <div class="mb-2">
                        <label for="timezone" class="form-label">{{ __('messages.time_zone') }}</label>
                        <select class="form-select" name="timezone">
                            @if(request('timezone'))
                            <option value="{{ request('timezone') }}" selected>{{ __('messages.selected') }} ({{ ucfirst(request('timezone')) }})</option>
                            @else
                            <option value="Etc/GMT" selected>Default (UTC)</option>
                            @endif
                            <option value="Etc/GMT">UTC</option>
                            <option value="Asia/Jakarta">Jakarta</option>
                            <option value="America/Cayenne">Cayenne</option>
                            <option value="Pacific/Honolulu">Hawaii</option>
                            <option value="Asia/Seoul">Seoul</option>
                        </select>
                    </div>
                    <div class="mb-2">
                        <div>
                            <label for="date" class="form-label">{{ __('messages.start_date') }}</label>
                            <input type="datetime-local" name="start_date" value="{{ request('start_date') }}">
                        </div>
                        <div>
                            <label for="date" class="form-label">{{ __('messages.end_date') }}</label>
                            <input type="datetime-local" name="end_date" value="{{ request('end_date') }}">
                        </div>
                    </div>
                    <div class="mb-2">
                        <label for="filter" class="form-label">Filter</label>
                        <select class="form-select" name="filter">
                            @if(request('filter'))
                            <option value="{{ request('filter') }}" selected>{{ __('messages.selected') }} ({{ __('messages.' . request('filter')) }})</option>
                            @else
                            <option value="date" selected>Default ({{ __('messages.sell_date') }})</option>
                            @endif
                            <option value="date">{{ __('messages.sell_date') }}</option>
                            <option value="price">{{ __('messages.sell_price') }}</option>
                            <option value="discount">{{ __('messages.sell_discount') }}</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="string" placeholder="{{ __('messages.search') }}" value="{{ request('string') }}">
                        <div class="input-group-append">
                            <button class="btn btn-outline-dark" type="submit">{{ __('messages.search') }}</button>
                        </div>
                    </div>  
                </form>
            </div>
            <div class="col-lg-12">
                @if($message = Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert" id="my-alert">
                        {!! session('success') !!}
                        <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                    </div>
                @endif
                <table id="company" class="display table">
                    <thead class="table-dark">
                        <tr>
                            <th>No</th>
                            <th>{{ __('messages.item_name') }}</th>
                            <th>{{ __('messages.sell_price') }}</th>
                            <th>{{ __('messages.sell_discount') }}</th>
                            <th>{{ __('messages.sell_by') }}
                            <th>{{ __('messages.sell_date') }}</th>
                            <th>{{ __('messages.action') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($sells as $sell)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $sell->item->name }}</td>
                            <td>Rp. {{ number_format($sell->price) }}</td>
                            <td>{{ round($sell->discount * 100) }}%</td>
                            <td>{{ $sell->employee->first_name }}</td>
                            <td>{{ \Carbon\Carbon::parse($sell->date)->setTimezone(request('timezone')) }}</td>
                            <td>
                                <form class="d-inline" action="{{ route('sell.destroy',$sell) }}" method="post">
                                    <a href="{{ route('sell.show',$sell) }}" class="btn btn-warning btn-sm"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('sell.edit',$sell) }}" class="btn btn-dark btn-sm"><i class="fas fa-edit"></i></a>
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger btn-sm" onclick="return confirm('{{ __('messages.confirm_to_delete_data') }}')" ><i class="fas fa-trash-alt"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $sells->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/sell/update.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('sell.update', $sell) }}" method="post" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="mb-3">
                    <label for="item_id" class="form-label">{{ __('messages.item_name') }}</label>
                    <select class="form-select" name="item_id">
                        @foreach($items as $item)
                            @if($sell->item->id == $item->id)
                                <option value="{{ $item->id }}" selected>{{ $item->name }}</option>
                            @else
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label for="employee_id" class="form-label">{{ __('messages.sell_by') }}</label>
                    <select class="form-select" name="employee_id">
                        @foreach($employees as $employee)
                            @if($sell->employee->id == $employee->id)
                                <option value="{{ $employee->id }}" selected>{{ $employee->first_name }}</option>
                            @else
                                <option value="{{ $employee->id }}">{{ $employee->first_name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group mb-3">
                    <label for="date">{{ __('messages.sell_date') }} &nbsp;</label><label class="text-danger">({{ __('messages.dont_touch_date') }})</label>
                    <input type="datetime-local" class="form-control" id="date" name="date" placeholder="199" autocomplete="off" value="{{ old('date', date('Y-m-d')) }}">
                    @error('date')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="price">{{ __('messages.sell_price') }} ({{ $sell->price }})</label>
                    <input type="text" class="form-control" id="price" name="price" placeholder="199" autocomplete="off" value="{{ old('price',0) }}">
                    @error('price')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="discount">{{ __('messages.sell_discount') }} ({{ $sell->discount }})</label>
                    <input type="text" class="form-control" id="discount" name="discount" placeholder="199" autocomplete="off" value="{{ old('discount',0) }}">
                    @error('discount')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection