routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\EmployeeLoginController;
use App\Http\Controllers\CompanyEmployeeController;
use App\Http\Controllers\EmployeeDashboardController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;

Route::redirect('/', '/login');
Auth::routes(['register' => false]);
Route::get('lang/{lang}', [LocalizationController::class, 'lang'])->name('lang.switch');

Route::prefix('employee')->group(function () {
    Route::middleware('guest:employee')->group(function() {
        Route::get('login/{id}', [EmployeeLoginController::class, 'login'])->name('login.employee_view');
        Route::post('login/{id}', [EmployeeLoginController::class, 'store'])->name('login.employee');
    });
    
    Route::middleware('auth:employee')->group(function() {
        Route::post('logout', [EmployeeLoginController::class, 'logout'])->name('employee.logout');
        Route::get('dashboard/home', [EmployeeDashboardController::class, 'index'])->name('employee.dashboard');
        Route::get('dashboard/list', [EmployeeDashboardController::class, 'show']);
    });
});

Route::prefix('dashboard')->middleware('auth:web')->group(function () {
    Route::get('home',[DashboardController::class,'index']);
    Route::get('company/{company}/show-employee', [CompaniesController::class, 'showEmployee'])->name('company.employee');
    Route::get('summary', [SellSummaryController::class, 'index'])->name('summary.index');
    Route::get('summary-detail/{employee_id}/{date}', [SellSummaryController::class, 'detail'])->name('summary.detail');
    Route::resource('employee', CompanyEmployeeController::class);
    Route::resource('company', CompaniesController::class);
    Route::resource('item', ItemController::class);
    Route::resource('sell', SellController::class);
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Employee extends Authenticatable
{
    use HasFactory;

    protected $guarded = ['id'];
    protected $hidden = ['password'];
    protected $with = ['companies'];

    public function companies()
    {
        return $this->belongsTo(Companies::class);
    }

    public function created_by()
    {
        return $this->belongsTo(User::class);
    }

    public function updated_by()
    {
        return $this->belongsTo(User::class);
    }

    public function sell()
    {
        return $this->hasMany(Sell::class);
    }

    public function sellsummary()
    {
        return $this->hasMany(SellSummary::class);
    }

    public static function filter($filter,$query,$page)
    {
        return self::where("$filter", 'like', "%$query%")->latest()->paginate($page)->withQueryString();
    }

    public static function filterByCompany($id,$filter,$query,$page)
    {
        return self::where([['companies_id', $id], ["$filter", 'like', "%$query%"]])->latest()->paginate($page)->withQueryString();
    }
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Companies;
use Illuminate\Http\Request;
use App\Notifications\CompanyCreated;
use Illuminate\Support\Facades\Storage;

class CompaniesController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page = $request->paginate;
        $query = $request->string;

        if($filter = $request->filter) {
            if($filter == 'name' || $filter == 'website' || $filter == 'created_at' || $filter == 'email') {
                $companies = Companies::filter($filter,$query,$page);
            } else {
                abort(404);
            }
        } else {
            $companies = Companies::latest()->paginate(5)->withQueryString();
        }

        return view('dashboard.company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'website' => 'required',
            'logo' => ' image|dimensions:min_width=100,min_height=100'
        ]);
        
        $input = $request->all();

        if ($request->file('logo')) {
            $input['logo'] = $request->file('logo')->store('logo');
        } else {
            $input['logo'] = "default.png";
        }

        $user = auth()->user();

        $input['created_by_id'] = $user->id;
        $input['updated_by_id'] = $user->id;

        Companies::create($input);

        $createdData = [
            'header' => 'New Company has been created!',
            'body' => 'New company named ' . $request->get('name') .  ' has been created!',
            'text' => 'Go to Company',
            'url' => url('/dashboard/company'),
            'thankyou' => 'Thank you'
        ];
        
        $user->notify(new CompanyCreated($createdData));
        
        return redirect()->route('company.index')->with('success', __('flash.company_created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function show(Companies $company)
    {
        return view('dashboard.company.detail', compact('company'));
    }

    public function showEmployee(Request $request)
    {
        $page = $request->paginate;
        $company_id = $request->segment(3);
        $query = $request->string;

        if(!Companies::where('id', $company_id)->first()) abort(404);

        if($filter = $request->filter) {
            if($filter == 'first_name' || $filter == 'last_name' || $filter == 'email' || $filter == 'phone' || $filter == 'created_at') {
                $employees = Employee::filterByCompany($company_id,$filter,$query,$page);
            } else {
                abort(404);
            }
        } else {
            $employees = Employee::where('companies_id', $company_id)->paginate(5);
        }

        return view('dashboard.company.show-employee', compact('employees'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function edit(Companies $company)
    {

        return view('dashboard.company.update', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Companies $company)
    {
        $request->validate([
            'name' => 'required',
            'logo' => 'image|dimensions:min_width=100,min_height=100'
        ]);

        $input = $request->all();

        if ($request->file('logo')) {
            if($company['logo'] != 'default.png') Storage::delete($company['logo']);
            $input['logo'] = $request->file('logo')->store('logo');
        } else {
            unset($input['logo']);
        }

        $input['updated_by_id'] = auth()->user()->id;

        $company->update($input);

        return redirect()->route('company.index')->with('success', __('flash.company_updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function destroy(Companies $company)
    {
        if($company['logo'] != 'default.png') Storage::delete($company['logo']);
        $company->delete();

        return redirect()->route('company.index')->with('success', __('flash.company_removed'));
    }

}

resources/views/dashboard/company/employee/create.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-7">
                <form action="{{ route('employee.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="companies_id" value="{{ $company_id }}">
                    <div class="form-group mb-3">
                        <label for="first_name">{{ __('messages.first_name') }}</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name" autocomplete="off" value="{{ old('first_name') }}">
                        @error('first_name')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-3">
                        <label for="last_name">{{ __('messages.last_name') }}</label>
                        <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name" autocomplete="off" value="{{ old('last_name') }}">
                        @error('last_name')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-4">
                        <label for="email">{{ __('messages.email') }}</label>
                        <input type="text" class="form-control" id="email" name="email" placeholder="example@example.com" autocomplete="off" value="{{ old('email') }}">
                        @error('email')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-4">
                        <label for="password">{{ __('messages.password') }}</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="abcde" autocomplete="off">
                        @error('password')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-4">
                        <label for="phone">{{ __('messages.phone_number') }}</label>
                        <input type="text" class="form-control" id="phone" name="phone" placeholder="123456789" autocomplete="off" value="{{ old('phone') }}">
                        @error('phone')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/company/employee/detail.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title text-uppercase font-weight-bold">{{ $employee->first_name }}  {{ $employee->last_name }}</h3>
            <div class="card-tools">
                <span class="badge badge-primary">Option</span>
            </div>
        </div>
        <div class="card-body">
            <img src="/img/tes.png" class="card-img-top mr-4" style="width:150px; float:left;" alt="...">
            <ul class="mt-5">
                <li>
                    {{ __('messages.company_name') }} : <a href="/dashboard/company/{{ $employee->companies->id }}" class="text-uppercase">{{ $employee->companies->name }}</a>
                </li>
                <li>Created by : {{ $employee->created_by->name }}</li>
                <li>Email : {{ $employee->email }}</li>
                <li>Phone : {{ $employee->phone }}</li>
            </ul>
        </div>
    </div>
@endsection

resources/views/dashboard/company/employee/index.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="content">
    <div class="container ml-2">
        <div class="col-lg-6">
            <form action="{{ route('employee.index') }}" method="GET">
                <label for="slug" class="form-label">Paginate</label>
                <input type="text" class="form-control mb-3" name="paginate" placeholder="{{ __('messages.paginate_per_page') }}" value="{{ request('paginate') }}">
                <div class="mb-2">
                    <label for="timezone" class="form-label">{{ __('messages.time_zone') }}</label>
                    <select class="form-select" name="timezone">
                        @if(request('timezone'))
                        <option value="{{ request('timezone') }}" selected>{{ __('messages.selected') }} ({{ ucfirst(request('timezone')) }})</option>
                        @else
                        <option value="Etc/GMT" selected>Default (UTC)</option>
                        @endif
                        <option value="Etc/GMT">UTC</option>
                        <option value="Asia/Jakarta">Jakarta</option>
                        <option value="America/Cayenne">Cayenne</option>
                        <option value="Pacific/Honolulu">Hawaii</option>
                        <option value="Asia/Seoul">Seoul</option>
                    </select>
                </div>
                <div class="mb-2">
                    <label for="filter" class="form-label">Filter</label>
                    <select class="form-select" name="filter">
                        @if(request('filter'))
                        <option value="{{ request('filter') }}" selected>{{ __('messages.selected') }} ({{ __('messages.' . request('filter')) }})</option>
                        @else
                        <option value="first_name" selected>Default ({{ __('messages.first_name') }})</option>
                        @endif
                        <option value="first_name">{{ __('messages.first_name') }}</option>
                        <option value="last_name">{{ __('messages.last_name') }}</option>
                        <option value="email">{{ __('messages.email') }}</option>
                        <option value="phone">{{ __('messages.phone') }}</option>
                        <option value="created_at">{{ __('messages.created_at') }}</option>
                    </select>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="string" placeholder="{{ __('messages.search') }}" value="{{ request('string') }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-dark" type="submit">{{ __('messages.search') }}</button>
                    </div>
                </div>  
            </form>
        </div>
        <div class="col-lg-12">
            @if($message = Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {!! session('success') !!}
                    <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                </div>
            @endif
            <table id="employee" class="display table">
                <thead class="table-dark">
                    <tr>
                        <th>No</th>
                        <th>{{ __('messages.first_name') }}</th>
                        <th>{{ __('messages.last_name') }}</th>
                        <th>{{ __('messages.company_name') }}</th>
                        <th>{{ __('messages.email') }}</th>
                        <th>{{ __('messages.phone') }}</th>
                        <th>{{ __('messages.created_at') }}</th>
                        <th>{{ __('messages.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($employees as $employee)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $employee->first_name }}</td>
                        <td>{{ $employee->last_name }}</td>
                        <td><a href="/dashboard/company/{{ $employee->companies->id }}">{{ $employee->companies->name }}</a></td>
                        <td>{{ $employee->email }}</td>
                        <td>{{ $employee->phone }}</td>
                        <td>{{ \Carbon\Carbon::parse($employee->created_at)->setTimezone(request('timezone')) }}</td>
                        <td>
                            <form class="d-inline" action="{{ route('employee.destroy',$employee) }}" method="post">
                                <a href="{{ route('employee.show',$employee) }}" class="btn btn-warning btn-sm"><i class="fas fa-eye"></i></a>
                                <a href="{{ route('employee.edit',$employee) }}" class="btn btn-dark btn-sm"><i class="fas fa-edit"></i></a>
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" onclick="return confirm('{{ __('messages.confirm_to_delete_data') }}')" ><i class="fas fa-trash-alt"></i></a>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
            {{ $employees->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/company/employee/update.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('employee.update',$employee) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group mb-3">
                    <label for="first_name">{{ __('messages.first_name') }}</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name" autocomplete="off" value="{{ $employee->first_name }}" required>
                    @error('first_name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="last_name">{{ __('messages.last_name') }}</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name" autocomplete="off" value="{{ $employee->last_name }}" required>
                    @error('last_name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-4">
                    <label for="email">{{ __('messages.email') }}</label>
                    <input type="text" class="form-control" id="email" name="email" placeholder="example@example.com" autocomplete="off" value="{{ $employee->email }}">
                    @error('email')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-4">
                    <label for="password">{{ __('messages.password') }} &nbsp;</label><label class="text-danger">({{ __('messages.dont_touch_password') }})</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="abcde" autocomplete="off" value="{{ $employee->password }}">
                    @error('password')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-4">
                    <label for="phone">{{ __('messages.phone_number') }}</label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="123456789" autocomplete="off" value="{{ $employee->phone }}">
                    @error('phone')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection