routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\EmployeeLoginController;
use App\Http\Controllers\CompanyEmployeeController;
use App\Http\Controllers\EmployeeDashboardController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;

Route::redirect('/', '/login');
Auth::routes(['register' => false]);
Route::get('lang/{lang}', [LocalizationController::class, 'lang'])->name('lang.switch');

Route::prefix('employee')->group(function () {
    Route::middleware('guest:employee')->group(function() {
        Route::get('login/{id}', [EmployeeLoginController::class, 'login'])->name('login.employee_view');
        Route::post('login/{id}', [EmployeeLoginController::class, 'store'])->name('login.employee');
    });
    
    Route::middleware('auth:employee')->group(function() {
        Route::post('logout', [EmployeeLoginController::class, 'logout'])->name('employee.logout');
        Route::get('dashboard/home', [EmployeeDashboardController::class, 'index'])->name('employee.dashboard');
        Route::get('dashboard/list', [EmployeeDashboardController::class, 'show']);
    });
});

Route::prefix('dashboard')->middleware('auth:web')->group(function () {
    Route::get('home',[DashboardController::class,'index']);
    Route::get('company/{company}/show-employee', [CompaniesController::class, 'showEmployee'])->name('company.employee');
    Route::get('summary', [SellSummaryController::class, 'index'])->name('summary.index');
    Route::get('summary-detail/{employee_id}/{date}', [SellSummaryController::class, 'detail'])->name('summary.detail');
    Route::resource('employee', CompanyEmployeeController::class);
    Route::resource('company', CompaniesController::class);
    Route::resource('item', ItemController::class);
    Route::resource('sell', SellController::class);
});

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Companies;
use Illuminate\Http\Request;
use App\Notifications\CompanyCreated;
use Illuminate\Support\Facades\Storage;

class CompaniesController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page = $request->paginate;
        $query = $request->string;

        if($filter = $request->filter) {
            if($filter == 'name' || $filter == 'website' || $filter == 'created_at' || $filter == 'email') {
                $companies = Companies::filter($filter,$query,$page);
            } else {
                abort(404);
            }
        } else {
            $companies = Companies::latest()->paginate(5)->withQueryString();
        }

        return view('dashboard.company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'website' => 'required',
            'logo' => ' image|dimensions:min_width=100,min_height=100'
        ]);
        
        $input = $request->all();

        if ($request->file('logo')) {
            $input['logo'] = $request->file('logo')->store('logo');
        } else {
            $input['logo'] = "default.png";
        }

        $user = auth()->user();

        $input['created_by_id'] = $user->id;
        $input['updated_by_id'] = $user->id;

        Companies::create($input);

        $createdData = [
            'header' => 'New Company has been created!',
            'body' => 'New company named ' . $request->get('name') .  ' has been created!',
            'text' => 'Go to Company',
            'url' => url('/dashboard/company'),
            'thankyou' => 'Thank you'
        ];
        
        $user->notify(new CompanyCreated($createdData));
        
        return redirect()->route('company.index')->with('success', __('flash.company_created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function show(Companies $company)
    {
        return view('dashboard.company.detail', compact('company'));
    }

    public function showEmployee(Request $request)
    {
        $page = $request->paginate;
        $company_id = $request->segment(3);
        $query = $request->string;

        if(!Companies::where('id', $company_id)->first()) abort(404);

        if($filter = $request->filter) {
            if($filter == 'first_name' || $filter == 'last_name' || $filter == 'email' || $filter == 'phone' || $filter == 'created_at') {
                $employees = Employee::filterByCompany($company_id,$filter,$query,$page);
            } else {
                abort(404);
            }
        } else {
            $employees = Employee::where('companies_id', $company_id)->paginate(5);
        }

        return view('dashboard.company.show-employee', compact('employees'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function edit(Companies $company)
    {

        return view('dashboard.company.update', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Companies $company)
    {
        $request->validate([
            'name' => 'required',
            'logo' => 'image|dimensions:min_width=100,min_height=100'
        ]);

        $input = $request->all();

        if ($request->file('logo')) {
            if($company['logo'] != 'default.png') Storage::delete($company['logo']);
            $input['logo'] = $request->file('logo')->store('logo');
        } else {
            unset($input['logo']);
        }

        $input['updated_by_id'] = auth()->user()->id;

        $company->update($input);

        return redirect()->route('company.index')->with('success', __('flash.company_updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function destroy(Companies $company)
    {
        if($company['logo'] != 'default.png') Storage::delete($company['logo']);
        $company->delete();

        return redirect()->route('company.index')->with('success', __('flash.company_removed'));
    }

}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        return view('dashboard.index',[
            'title' => 'Dashboard'
        ]);
    }
}

resources/views/dashboard/company/create.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-7">
                <form action="{{ route('company.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group mb-3">
                        <label for="name">{{ __('messages.company_name') }}</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="{{ __('messages.company_name') }}" autocomplete="off" value="{{ old('name') }}">
                        @error('name')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-3">
                        <label for="email">{{ __('messages.email') }}</label>
                        <input type="text" class="form-control" id="email" name="email" placeholder="example@example.com" autocomplete="off" value="{{ old('email') }}">
                        @error('email')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-4">
                        <label for="website">Website</label>
                        <input type="text" class="form-control" id="website" name="website" placeholder="www.example.com" autocomplete="off" value="{{ old('website') }}">
                        @error('website')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label class="d-block" for="logo" class="formFile">{{ __('messages.insert_logo_here') }}</label>
                        <img src="" class="img-preview mb-3" style="width: 100px;">
                        <input type="file" id="logo" name="logo" onchange="imgPreview()">
                        @error('logo')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        function imgPreview() {
            const image = document.querySelector('#logo')
            const preview = document.querySelector('.img-preview')

            preview.style.display = 'block'

            const oFReader = new FileReader();
            oFReader.readAsDataURL(image.files[0])

            oFReader.onload = function(oFREvent) {
                preview.src = oFREvent.target.result;
            }
        }
    </script>
@endsection

resources/views/dashboard/company/detail.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title text-uppercase font-weight-bold">{{ $company->name }}</h3>
            <div class="card-tools">
                <a href="{{ route('company.employee', $company) }}">{{ __('messages.view_company_employee') }}</a>
            </div>
        </div>
        <div class="card-body">
            @if($company->logo == 'default.png')
                <img class="card-img-top mr-4" src="{{ asset('img/default.png') }}" style="width: 150px; float:left;">
            @else
                <img class="card-img-top mr-4" src="{{ asset('storage/' . $company->logo) }}" style="width:150px; float: left;"></td>
            @endif
            <ul class="mt-5">
                <li>Email : {{ $company->email }}</li>
                <li>Created by : {{ $company->created_by->name }}</li>
                <li>Website : {{ $company->website }}</li>
            </ul>
        </div>
    </div>
@endsection

resources/views/dashboard/company/index.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="content">
    <div class="container ml-2">
        <div class="row">
            <div class="col-lg-12 mb-3">
                <a href="/dashboard/company/create" class="text-white"><button type="button" class="btn btn-dark">{{ __('messages.add_company') }}</a></button>
            </div>
            <div class="col-lg-6">
                <form action="{{ route('company.index') }}" method="GET">
                    <label for="slug" class="form-label">Paginate</label>
                    <input type="text" class="form-control mb-3" name="paginate" placeholder="{{ __('messages.paginate_per_page') }}" value="{{ request('paginate') }}">
                    <div class="mb-2">
                        <label for="timezone" class="form-label">{{ __('messages.time_zone') }}</label>
                        <select class="form-select" name="timezone">
                            @if(request('timezone'))
                            <option value="{{ request('timezone') }}" selected>{{ __('messages.selected') }} ({{ ucfirst(request('timezone')) }})</option>
                            @else
                            <option value="Etc/GMT" selected>Default (UTC)</option>
                            @endif
                            <option value="Etc/GMT">UTC</option>
                            <option value="Asia/Jakarta">Jakarta</option>
                            <option value="America/Cayenne">Cayenne</option>
                            <option value="Pacific/Honolulu">Hawaii</option>
                            <option value="Asia/Seoul">Seoul</option>
                        </select>
                    </div>
                    <div class="mb-2">
                        <label for="filter" class="form-label">Filter</label>
                        <select class="form-select" name="filter">
                            @if(request('filter'))
                            <option value="{{ request('filter') }}" selected>{{ __('messages.selected') }} ({{ __('messages.' . request('filter')) }})</option>
                            @else
                            <option value="name" selected>Default ({{ __('messages.company_name') }})</option>
                            @endif
                            <option value="name">{{ __('messages.company_name') }}</option>
                            <option value="email">{{ __('messages.email') }}</option>
                            <option value="website">Website</option>
                            <option value="created_at">{{ __('messages.created_at') }}</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="string" placeholder="{{ __('messages.search') }}" value="{{ request('string') }}">
                        <div class="input-group-append">
                            <button class="btn btn-outline-dark" type="submit">{{ __('messages.search') }}</button>
                        </div>
                    </div>  
                </form>
            </div>
            <div class="col-lg-12">
                @if($message = Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert" id="my-alert">
                        {!! session('success') !!}
                        <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                    </div>
                @endif
                <table id="company" class="display table">
                    <thead class="table-dark">
                        <tr>
                            <th>No</th>
                            <th>{{ __('messages.company_name') }}</th>
                            <th>{{ __('messages.email') }}</th>
                            <th>Logo</th>
                            <th>Website</th>
                            <th>{{ __('messages.created_at') }}</th>
                            <th>{{ __('messages.action') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($companies as $company)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $company->name }}</td>
                            <td>{{ $company->email }}</td>
                            <td>
                                @if($company->logo == 'default.png')
                                <img src="{{ asset('img/default.png') }}" style="width: 35px;">
                                @else
                                <img src="{{ asset('storage/' . $company->logo) }}" style="width:35px"></td>
                                @endif
                            <td>{{ $company->website }}</td>
                            <td>{{ \Carbon\Carbon::parse($company->created_at)->setTimezone(request('timezone')) }}</td>
                            <td>
                                <form class="d-inline" action="{{ route('company.destroy',$company) }}" method="post">
                                    <a href="{{ route('employee.create',$company) }}" class="btn btn-primary btn-sm" alt="Create Company"><i class="fas fa-user-plus"></i></a>
                                    <a href="{{ route('company.show',$company) }}" class="btn btn-warning btn-sm"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('company.edit',$company) }}" class="btn btn-dark btn-sm"><i class="fas fa-edit"></i></a>
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger btn-sm" onclick="return confirm('{{ __('messages.confirm_to_delete_data') }}')" ><i class="fas fa-trash-alt"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $companies->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/company/show-employee.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="content">
    <div class="container ml-2 mt-3">
        <div class="mb-3">
            <a href="{{ route('company.index') }}"><button class="btn btn-dark">{{ __('messages.back_to_company') }}</button></a>
        </div>
        <div class="col-lg-6">
            <form action="{{ url()->current() }}" method="GET">
                <label for="slug" class="form-label">Paginate</label>
                <input type="text" class="form-control mb-3" name="paginate" placeholder="{{ __('messages.paginate_per_page') }}" value="{{ request('paginate') }}">
                <div class="mb-2">
                    <label for="timezone" class="form-label">{{ __('messages.time_zone') }}</label>
                    <select class="form-select" name="timezone">
                        @if(request('timezone'))
                        <option value="{{ request('timezone') }}" selected>{{ __('messages.selected') }} ({{ ucfirst(request('timezone')) }})</option>
                        @else
                        {{-- <option value="Etc/GMT" selected>Default (UTC)</option> --}}<p>Hello</p>
                        @endif
                        <option value="Etc/GMT">UTC</option>
                        <option value="Asia/Jakarta">Jakarta</option>
                        <option value="America/Cayenne">Cayenne</option>
                        <option value="Pacific/Honolulu">Hawaii</option>
                        <option value="Asia/Seoul">Seoul</option>
                    </select>
                </div>
                <div class="mb-2">
                    <label for="filter" class="form-label">Filter</label>
                    <select class="form-select" name="filter">
                        @if(request('filter'))
                        <option value="{{ request('filter') }}" selected>{{ __('messages.selected') }} ({{ __('messages.' . request('filter')) }})</option>
                        @else
                        <option value="first_name" selected>Default ({{ __('messages.first_name') }})</option>
                        @endif
                        <option value="first_name">{{ __('messages.first_name') }}</option>
                        <option value="last_name">{{ __('messages.last_name') }}</option>
                        <option value="email">{{ __('messages.email') }}</option>
                        <option value="phone">{{ __('messages.phone') }}</option>
                        <option value="created_at">{{ __('messages.created_at') }}</option>
                    </select>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="string" placeholder="{{ __('messages.search') }}" value="{{ request('string') }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-dark" type="submit">{{ __('messages.search') }}</button>
                    </div>
                </div>  
            </form>
        </div>
        <div class="col-lg-12">
            <table id="employee" class="display table">
                <thead class="table-dark">
                    <tr>
                        <th>No</th>
                        <th>{{ __('messages.first_name') }}</th>
                        <th>{{ __('messages.last_name') }}</th>
                        <th>Email</th>
                        <th>{{ __('messages.phone') }}</th>
                        <th>{{ __('messages.created_at') }}</th>
                        <th>{{ __('messages.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($employees as $employee)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $employee->first_name }}</td>
                        <td>{{ $employee->last_name }}</td>
                        <td>{{ $employee->email }}</td>
                        <td>{{ $employee->phone }}</td>
                        <td>{{ \Carbon\Carbon::parse($employee->created_at)->setTimezone(request('timezone')) }}
                        <td>
                            <form class="d-inline" action="{{ route('employee.destroy',$employee) }}" method="post">
                                <a href="{{ route('employee.show',$employee) }}" class="btn btn-warning btn-sm"><i class="fas fa-eye"></i></a>
                                <a href="{{ route('employee.edit',$employee) }}" class="btn btn-dark btn-sm"><i class="fas fa-edit"></i></a>
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" onclick="return confirm('{{ __('messages.confirm_to_delete_data') }}')" ><i class="fas fa-trash-alt"></i></a>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $employees->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/company/update.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('company.update', $company) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group mb-3">
                    <label for="name">{{ __('messages.company_name') }}</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Company name" value="{{ $company->name }}">
                    @error('name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="email">{{ __('messages.email') }}</label>
                    <input type="text" class="form-control" id="email" name="email" placeholder="example@example.com" value="{{ $company->email }}">
                    @error('email')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-4">
                    <label for="website">Website</label>
                    <input type="text" class="form-control" id="website" name="website" placeholder="www.example.com" value="{{ $company->website }}">
                    @error('website')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mb-3">
                    <label class="d-block" for="logo" class="formFile">{{ __('messages.insert_logo_here') }}</label>
                    <img src="{{ asset('storage/' . $company->logo) }}" class="img-preview mb-3 d-block" style="width: 100px;">
                    <input type="file" id="logo" name="logo" onchange="imgPreview()">
                    @error('logo')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
</div>

<script>
    function imgPreview() {
        const image = document.querySelector('#logo')
        const preview = document.querySelector('.img-preview')

        preview.style.display = 'block'

        const oFReader = new FileReader();
        oFReader.readAsDataURL(image.files[0])

        oFReader.onload = function(oFREvent) {
            preview.src = oFREvent.target.result;
        }
    }
</script>
@endsection